variables:
  MAVEN_REPO_LOCAL_PATH: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=$MAVEN_REPO_LOCAL_PATH"
  MAVEN_CLI_OPTS: "-s .mvn/settings.xml --batch-mode --errors --fail-at-end --show-version"
  DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME"

stages:
  - build     # compile, unit-tests, integration-tests, package
  - analyze   # run sonarqube analysis
  - push      # build docker image and push image to artifactory
  - cleanup   # delete existing ressources from openshift namespace
  - deploy    # push to openshift

maven-build:
  stage: build
  image: openjdk:8-jdk-alpine
  cache:
    key: $CI_PROJECT_PATH
    paths:
      - $MAVEN_REPO_LOCAL_PATH
  artifacts:
    expire_in: 1 day
    paths:
      - target/*
  script: "./mvnw $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent verify"


sonarqube:
  stage: analyze
  image: openjdk:8-jdk-alpine
  cache:
    key: $CI_PROJECT_PATH
    paths:
      - $MAVEN_REPO_LOCAL_PATH
  script:
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then SONAR_BRANCH_NAME=""; else SONAR_BRANCH_NAME="-Dsonar.branch.name=$CI_COMMIT_REF_NAME"; fi
    - "./mvnw $MAVEN_CLI_OPTS $SONAR_MAVEN_GOAL $SONAR_BRANCH_NAME -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN"

################################################################################
# PUSH

docker-build:
  stage: push
  image: docker:latest
  script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASS" $DOCKER_REGISTRY_URL
    - docker build --pull -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_REPO/$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_REPO/$DOCKER_IMAGE_NAME"
    
################################################################################
# CLEANUP

cleanup:
  stage: cleanup
  image: $DOCKER_REGISTRY_URL/qaware-internal-docker/oc:latest
  variables:
    GIT_STRATEGY: none
  dependencies: []
  script:
    - oc login $OPENSHIFT_URL -u $OPENSHIFT_USER -p $OPENSHIFT_PASS
    - oc project $OPENSHIFT_NAMESPACE 2> /dev/null || oc new-project $OPENSHIFT_NAMESPACE
    - oc delete all --all
    - until oc get pods 2>&1 | grep -c "No resources found."; do sleep 1; done

################################################################################
# DEPLOY

cap-deploy:
  stage: deploy
  image: $DOCKER_REGISTRY_URL/qaware-internal-docker/oc:latest
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://lombok-service.cap.qaware.de
  variables:
    GIT_STRATEGY: none
  dependencies: []
  script:
    - oc login $OPENSHIFT_URL -u $OPENSHIFT_USER -p $OPENSHIFT_PASS
    - oc project $OPENSHIFT_NAMESPACE 2> /dev/null || oc new-project $OPENSHIFT_NAMESPACE
    - >
      oc new-app
      --docker-image=$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_REPO/$DOCKER_IMAGE_NAME
      --name=lombok-service
    - until oc get pods 2>&1 | grep lombok-service | grep -v deploy | grep 1/1 | grep Running; do sleep 1; done
    - until oc create route edge --service=lombok-service --insecure-policy=Redirect --hostname=lombok-service.cap.qaware.de; do sleep 1; done
  only:
    - master
